// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Used by `prisma migrate` only. Prefer DIRECT_URL (a non-pooled Neon
    // connection) so migrations don't acquire advisory locks through the
    // pooler, where orphaned sessions can leave the lock held. Falls back
    // to DATABASE_URL for local dev.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
